import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LeftPanel from "@/components/LeftPanel";
import { Spotlight } from "@/components/ui/Spotlight";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Spotlight
          className="-top-40 -z-50 left-0 md:left-60 md:-top-20"
          fill="white"
        />

        <div className="flex w-[95%] justify-center p-14 items-center m-auto">
          <div className="w-[22%]">
            <LeftPanel />
          </div>
          <div className="w-[72%] justify-center  items-center m-6">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
