import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import LeftBio from "@/components/LeftBio";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <div className="pl-[4.5rem]  pr-[4.5rem] pt-8 pb-8">
<Header/>
    </div>
        <div className="flex pl-[4.5rem]  pr-[4.5rem] w-full">
          <div className="w-[35%]">
            <LeftBio/>
          </div>
          <div className="w-[65%]">{children}</div>
        </div>
      </body>
    </html>
  );
}
